graph TB

subgraph diagram
    Background["背景：賽默飛世爾收購全球知名CRO公司PPD事件"]
    Cause1["原因1：擴大市場份額"]
    Cause2["原因2：提高研發能力"]
    Cause3["原因3：增強全球競爭力"]
    Future1["未來影響1：加強賽默飛世爾在CRO領域的地位"]
    Future2["未來影響2：促進醫藥研發和創新"]
    Future3["未來影響3：帶動全球醫藥產業發展"]
    
    Background -->|"賽默飛世爾可以通過收購PPD公司來擴大其在CRO領域的市場份額"| Cause1
    Background -->|"賽默飛世爾可以借助PPD公司的研發能力和技術，提高自身的研發水平"| Cause2
    Background -->|"賽默飛世爾收購PPD公司可以增強其在全球醫藥市場的競爭力"| Cause3
    Cause1 -->|"可能導致"| Future1
    Cause2 -->|"可能導致"| Future2
    Cause3 -->|"可能導致"| Future3

end

subgraph Impact
    Impact1["加強賽默飛世爾在CRO領域的地位"]
    Impact2["促進醫藥研發和創新"]
    Impact3["帶動全球醫藥產業發展"]
    
    Future1 -->|"賽默飛世爾在CRO領域的市場份額增加，提高其在行業中的地位"| Impact1
    Future2 -->|"賽默飛世爾的研發能力提升，有助於推動醫藥研發和創新"| Impact2
    Future3 -->|"賽默飛世爾的全球競爭力提升，有助於帶動全球醫藥產業的發展"| Impact3
end

Background:::neutral
Cause1:::forest
Cause2:::forest
Cause3:::forest
Future1:::dark
Future2:::dark
Future3:::dark
Impact1:::base
Impact2:::base
Impact3:::base
